
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package j_frame;

/**
 *
 * @author byvagner
 */
import clases.Encargado ;

public class JF_Encargado extends javax.swing.JFrame {

    /**
     * Creates new form JF_Encargado
     */
    Encargado e = new Encargado();
    
    public JF_Encargado() {
        initComponents();
        this.setLocationRelativeTo(null);
        e.MostrarEncargado(jTablesEncargadoE);
        this.LogearEnc();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldNOMBREE = new javax.swing.JTextField();
        jTextFieldAPELLIDOE = new javax.swing.JTextField();
        jTextFieldSEXOE = new javax.swing.JTextField();
        jTextFieldTIPOE = new javax.swing.JTextField();
        jTextFieldCORREOE = new javax.swing.JTextField();
        jTextFieldCELULARE = new javax.swing.JTextField();
        jTextFieldFECHA_IE = new javax.swing.JTextField();
        jTextFieldFECHA_FE = new javax.swing.JTextField();
        jTextFielCIE = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablesEncargadoE = new javax.swing.JTable();
        jButtonNuevoE = new javax.swing.JButton();
        jButtonguardarE = new javax.swing.JButton();
        jButtonModificarE = new javax.swing.JButton();
        jButtonEliminarE = new javax.swing.JButton();
        jButtonSeleccionar = new javax.swing.JButton();
        jButtonSeleccionarId = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabeltxtencargado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Encargado ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 60, -1));

        jLabel3.setText("APELLIDO");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel4.setText("SEXO");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jLabel5.setText("CI");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        jLabel6.setText("TIPO");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        jLabel7.setText("CORREO");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, -1, -1));

        jLabel8.setText("CELULAR");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, -1, -1));

        jLabel9.setText("FEHCA INICO");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, -1, -1));

        jLabel10.setText("FECHA FINAL");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, -1, -1));

        jLabel11.setText("NOMBRE");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));
        jPanel2.add(jTextFieldNOMBREE, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 190, -1));
        jPanel2.add(jTextFieldAPELLIDOE, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 190, -1));
        jPanel2.add(jTextFieldSEXOE, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 210, -1));

        jTextFieldTIPOE.setEditable(false);
        jTextFieldTIPOE.setText("Encargado");
        jPanel2.add(jTextFieldTIPOE, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 210, -1));
        jPanel2.add(jTextFieldCORREOE, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 190, -1));
        jPanel2.add(jTextFieldCELULARE, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 190, -1));
        jPanel2.add(jTextFieldFECHA_IE, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 170, -1));
        jPanel2.add(jTextFieldFECHA_FE, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 170, -1));
        jPanel2.add(jTextFielCIE, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 220, -1));

        jTablesEncargadoE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablesEncargadoE);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 940, 100));

        jButtonNuevoE.setText("nuevo");
        jButtonNuevoE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoEActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonNuevoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 120, 70, -1));

        jButtonguardarE.setText("guardar");
        jButtonguardarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonguardarEActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonguardarE, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 170, 70, -1));

        jButtonModificarE.setText("modificar");
        jButtonModificarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarEActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonModificarE, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 120, 80, -1));

        jButtonEliminarE.setText("eliminar");
        jButtonEliminarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarEActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonEliminarE, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 170, 90, -1));

        jButtonSeleccionar.setText("seleccionar");
        jButtonSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeleccionarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, 90, -1));

        jButtonSeleccionarId.setText("Seleccionar ID ");
        jButtonSeleccionarId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeleccionarIdActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSeleccionarId, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 480, 110, -1));

        jButton2.setText("Atras");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 274, 110, 30));
        jPanel2.add(jLabeltxtencargado, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 450, 210, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void limpiar(){
        jTextFielCIE.setText("");
        jTextFieldNOMBREE.setText("");
        jTextFieldAPELLIDOE.setText("");
        jTextFieldSEXOE.setText("");
        //jTextFieldTIPOE.setText("Encargado");
        jTextFieldCORREOE.setText("");
        jTextFieldCELULARE.setText("");
        jTextFieldFECHA_IE.setText("");
        jTextFieldFECHA_FE.setText("");
    }
    public void LogearEnc(){
        switch(JF_principal.valiladorPrincipal){
            case"1":
                break;
            case"2":
                break;
            case"3":
            case"4":
                JF_Encargado.jButtonEliminarE.setEnabled(false);
                break;
            default:
                break;               
        }
    }
    private void jButtonNuevoEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoEActionPerformed
       this.limpiar();
    }//GEN-LAST:event_jButtonNuevoEActionPerformed

    private void jButtonguardarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonguardarEActionPerformed
        e.setCi(jTextFielCIE.getText());
        e.setNombre(jTextFieldNOMBREE.getText());
        e.setApellido(jTextFieldAPELLIDOE.getText());
        e.setSexo(jTextFieldSEXOE.getText());
        e.setTipo(jTextFieldTIPOE.getText());
        e.setCorreo(jTextFieldCORREOE.getText());
        e.setCel_ref(jTextFieldCELULARE.getText());
        e.setFecha_i(jTextFieldFECHA_IE.getText());
        e.setFEcha_f(jTextFieldFECHA_FE.getText());   
        e.insertarEncargado();
        e.MostrarEncargado(jTablesEncargadoE);
        this.limpiar();
    }//GEN-LAST:event_jButtonguardarEActionPerformed

    private void jButtonModificarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarEActionPerformed
        e.setCi(jTextFielCIE.getText());
        e.setNombre(jTextFieldNOMBREE.getText());
        e.setApellido(jTextFieldAPELLIDOE.getText());
        e.setSexo(jTextFieldSEXOE.getText());
        e.setTipo(jTextFieldTIPOE.getText());
        e.setCorreo(jTextFieldCORREOE.getText());
        e.setCel_ref(jTextFieldCELULARE.getText());
        e.setFecha_i(jTextFieldFECHA_IE.getText());
        e.setFEcha_f(jTextFieldFECHA_FE.getText());   
        e.ModificarEncargado(); 
        e.MostrarEncargado(jTablesEncargadoE);
        this.limpiar();       
    }//GEN-LAST:event_jButtonModificarEActionPerformed

    private void jButtonEliminarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarEActionPerformed
        // TODO add your handling code here:
        e.setCi(jTextFielCIE.getText());
        e.EliminarEncargado();
        e.MostrarEncargado(jTablesEncargadoE);
        this.limpiar();
        
    }//GEN-LAST:event_jButtonEliminarEActionPerformed

    private void jButtonSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeleccionarActionPerformed
        // TODO add your handling code here:
        int fila =jTablesEncargadoE.getSelectedRow();
        if (fila > -1){
            String ci = jTablesEncargadoE.getValueAt(fila, 0).toString();
            String Nombre = jTablesEncargadoE.getValueAt(fila, 1).toString();
            String Apellido = jTablesEncargadoE.getValueAt(fila, 2).toString();
            String sexo = jTablesEncargadoE.getValueAt(fila, 3).toString();
            String Tipo = jTablesEncargadoE.getValueAt(fila, 4).toString();
            String correo = jTablesEncargadoE.getValueAt(fila, 5).toString();
            String cel_ref = jTablesEncargadoE.getValueAt(fila, 6).toString();
            String Fecha_i = jTablesEncargadoE.getValueAt(fila, 7).toString();
            String fecha_f = jTablesEncargadoE.getValueAt(fila, 8) != null ? jTablesEncargadoE.getValueAt(fila, 8).toString() : "";

            jTextFielCIE.setText(ci);
            jTextFieldNOMBREE.setText(Nombre);
            jTextFieldAPELLIDOE.setText(Apellido);
            jTextFieldSEXOE.setText(sexo);
            jTextFieldTIPOE.setText(Tipo);
            jTextFieldCORREOE.setText(correo);
            jTextFieldCELULARE.setText(cel_ref);
            jTextFieldFECHA_IE.setText(Fecha_i);
            jTextFieldFECHA_FE.setText(fecha_f);
           
        }
    }//GEN-LAST:event_jButtonSeleccionarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new JF_PrincipalPersonal().setVisible(true);
        JF_Encargado.jButtonSeleccionarId.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonSeleccionarIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeleccionarIdActionPerformed
        int fila =jTablesEncargadoE.getSelectedRow();
        if (fila > -1){
           String id = jTablesEncargadoE.getValueAt(fila, 0).toString();
           if (JF_labor.OficialLabor!= null && JF_labor.OficialLabor.isVisible()) {
            JF_labor.OficialLabor.jTextFielciDencargado.setText(id);
            JF_Encargado.jButtonNuevoE.setEnabled(true);
            JF_Encargado.jButtonModificarE.setEnabled(true);
            JF_Encargado.jButtonguardarE.setEnabled(true);
            JF_Encargado.jButtonEliminarE.setEnabled(true);
            JF_Encargado.jButtonSeleccionar.setEnabled(true);
            JF_Encargado.jButton2.setEnabled(true);
            JF_Encargado.jLabeltxtencargado.setText("");
           }
           
        }
         this.dispose();
    }//GEN-LAST:event_jButtonSeleccionarIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Encargado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Encargado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Encargado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Encargado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Encargado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButton2;
    public static javax.swing.JButton jButtonEliminarE;
    public static javax.swing.JButton jButtonModificarE;
    public static javax.swing.JButton jButtonNuevoE;
    public static javax.swing.JButton jButtonSeleccionar;
    public static javax.swing.JButton jButtonSeleccionarId;
    public static javax.swing.JButton jButtonguardarE;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JLabel jLabeltxtencargado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablesEncargadoE;
    private javax.swing.JTextField jTextFielCIE;
    private javax.swing.JTextField jTextFieldAPELLIDOE;
    private javax.swing.JTextField jTextFieldCELULARE;
    private javax.swing.JTextField jTextFieldCORREOE;
    private javax.swing.JTextField jTextFieldFECHA_FE;
    private javax.swing.JTextField jTextFieldFECHA_IE;
    private javax.swing.JTextField jTextFieldNOMBREE;
    private javax.swing.JTextField jTextFieldSEXOE;
    private javax.swing.JTextField jTextFieldTIPOE;
    // End of variables declaration//GEN-END:variables
}
