/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package j_frame;

/**
 *
 * @author byvagner
 */
import clases.Formacion;

public class JF_formacion extends javax.swing.JFrame {

    /**
     * Creates new form JF_formacion
     */
    Formacion f = new Formacion();
    
    public JF_formacion() {
        if(JF_formacion.OficialFormacion != null){
            JF_formacion.OficialFormacion.dispose();
        }
        OficialFormacion=this;
        initComponents();
        this.setLocationRelativeTo(null);
        f.MostrarJtableTI(jTableFormacion);
        this.LogearFormacion();
    }
    
    public static JF_formacion OficialFormacion ;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFormacion = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jTextFieldTURNO = new javax.swing.JTextField();
        jTextFieldIDGRADO = new javax.swing.JTextField();
        jTextFieldIDUE = new javax.swing.JTextField();
        jTextFieldIDNIÑOS = new javax.swing.JTextField();
        jTextFieldIDF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonguardar = new javax.swing.JButton();
        jButtonmodificar = new javax.swing.JButton();
        jButtoneliminar = new javax.swing.JButton();
        jButtonnuevo = new javax.swing.JButton();
        jButtonseleccionar = new javax.swing.JButton();
        jButtonjfgrado = new javax.swing.JButton();
        jButtonjfue = new javax.swing.JButton();
        jButtonjfniños = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("formacion");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 60, 40));

        jTableFormacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableFormacion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 480, 160));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 552, 880, 10));
        jPanel1.add(jTextFieldTURNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 70, -1));

        jTextFieldIDGRADO.setEditable(false);
        jPanel1.add(jTextFieldIDGRADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 50, -1));

        jTextFieldIDUE.setEditable(false);
        jPanel1.add(jTextFieldIDUE, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 50, -1));

        jTextFieldIDNIÑOS.setEditable(false);
        jPanel1.add(jTextFieldIDNIÑOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 50, -1));
        jPanel1.add(jTextFieldIDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 40, -1));

        jLabel2.setText("Turno");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel3.setText("ID grado");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel4.setText("ID u. educativa");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel5.setText("IID niños");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel6.setText("ID");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jButtonguardar.setText("Guardar");
        jButtonguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonguardarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 90, -1));

        jButtonmodificar.setText("Modificar");
        jButtonmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonmodificarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 90, -1));

        jButtoneliminar.setText("Eliminar");
        jButtoneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoneliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtoneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 90, -1));

        jButtonnuevo.setText("nuevo");
        jButtonnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonnuevoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 60, -1));

        jButtonseleccionar.setText("SELECCIONAR ");
        jButtonseleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonseleccionarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonseleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, 150, -1));

        jButtonjfgrado.setText("Tabla grado");
        jButtonjfgrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonjfgradoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonjfgrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));

        jButtonjfue.setText("tabla u. educativa");
        jButtonjfue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonjfueActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonjfue, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        jButtonjfniños.setText("tabla niños");
        jButtonjfniños.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonjfniñosActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonjfniños, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, -1));

        jButton4.setText("atras");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 450, 70, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void limpiar (){
        jTextFieldIDF.setText("");
        jTextFieldTURNO.setText("");
        jTextFieldIDGRADO.setText("");
        jTextFieldIDUE.setText("");
        jTextFieldIDNIÑOS.setText("");
    }
    public void LogearFormacion(){
        switch(JF_principal.valiladorPrincipal){
            case"1":
                JF_formacion.jButtonjfgrado.setEnabled(false);
                JF_formacion.jButtonjfue.setEnabled(false);
                JF_formacion.jButtonjfniños.setEnabled(false);
                JF_formacion.jButtonnuevo.setEnabled(false);
                JF_formacion.jButtonmodificar.setEnabled(false);
                JF_formacion.jButtonguardar.setEnabled(false);
                JF_formacion.jButtoneliminar.setEnabled(false);
                JF_formacion.jButtonseleccionar.setEnabled(false);
                break;
            case"2":
                break;
            case"3":
            case"4":
                JF_formacion.jButtoneliminar.setEnabled(false);
                break;
            default:
                break;               
        }
    }
    private void jButtonnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonnuevoActionPerformed
        this.limpiar();
    }//GEN-LAST:event_jButtonnuevoActionPerformed

    private void jButtonseleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonseleccionarActionPerformed
        // TODO add your handling code here:
                int fila =jTableFormacion.getSelectedRow();
        if (fila > -1){
            String idF = jTableFormacion.getValueAt(fila, 0).toString();
            String Turno = jTableFormacion.getValueAt(fila, 1).toString();
            String idGrado = jTableFormacion.getValueAt(fila, 2).toString();
            String idUE = jTableFormacion.getValueAt(fila, 3).toString();
            String idniños = jTableFormacion.getValueAt(fila, 4).toString();
            
        jTextFieldIDF.setText(idF);
        jTextFieldTURNO.setText(Turno);
        jTextFieldIDGRADO.setText(idGrado);
        jTextFieldIDUE.setText(idUE);
        jTextFieldIDNIÑOS.setText(idniños);
            
         
        }
    }//GEN-LAST:event_jButtonseleccionarActionPerformed

    private void jButtonguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonguardarActionPerformed
        // TODO add your handling code here:
        f.setIdF(jTextFieldIDF.getText());
        f.setTurno(jTextFieldTURNO.getText());
        f.setIdGrado(jTextFieldIDGRADO.getText());
        f.setIdUE(jTextFieldIDUE.getText());
        f.setIdniños(jTextFieldIDNIÑOS.getText());
        
        f.guardar();
        f.MostrarJtableTI(jTableFormacion);
        this.limpiar();
    }//GEN-LAST:event_jButtonguardarActionPerformed

    private void jButtonmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonmodificarActionPerformed
        // TODO add your handling code here:
        f.setIdF(jTextFieldIDF.getText());
        f.setTurno(jTextFieldTURNO.getText());
        f.setIdGrado(jTextFieldIDGRADO.getText());
        f.setIdUE(jTextFieldIDUE.getText());
        f.setIdniños(jTextFieldIDNIÑOS.getText());
        
        f.modificar();
        f.MostrarJtableTI(jTableFormacion);
        this.limpiar();
    }//GEN-LAST:event_jButtonmodificarActionPerformed

    private void jButtoneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoneliminarActionPerformed
        // TODO add your handling code here:
        f.setIdF(jTextFieldIDF.getText());
        f.eliminar();
        f.MostrarJtableTI(jTableFormacion);
        this.limpiar();
    }//GEN-LAST:event_jButtoneliminarActionPerformed

    private void jButtonjfgradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonjfgradoActionPerformed
        new JF_grado().setVisible(true);
        JF_grado.jButton1.setEnabled(false);
        JF_grado.jButton2.setEnabled(false);
        JF_grado.jButton3.setEnabled(false);
        JF_grado.jButtonEliminar.setEnabled(false);
        JF_grado.jButton5.setEnabled(false);
        JF_grado.jButton7.setEnabled(false);
        JF_grado.jLabeltxtGradp.setText("ESCOJA ID PARA SELECCIONAR");
    }//GEN-LAST:event_jButtonjfgradoActionPerformed

    private void jButtonjfueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonjfueActionPerformed
        new JF_UE().setVisible(true);
        JF_UE.jButtonnuevo.setEnabled(false);
        JF_UE.jButtonGuardar.setEnabled(false);
        JF_UE.jButtonModificar.setEnabled(false);
        JF_UE.jButtonEliminarrrr.setEnabled(false);
        JF_UE.jButton2.setEnabled(false);
        JF_UE.jButtonSeleccioar.setEnabled(false);
        JF_UE.jLabel7.setText("ESCOJA UN ID PARA SELECCIONAR");
    }//GEN-LAST:event_jButtonjfueActionPerformed

    private void jButtonjfniñosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonjfniñosActionPerformed
        new JF_niños().setVisible(true);
        JF_niños.Tutor.setEnabled(false);
        JF_niños.jButtonPersonal.setEnabled(false);
        JF_niños.jButtonseleccionar.setEnabled(false);
        JF_niños.Nuevo.setEnabled(false);
        JF_niños.Guardar.setEnabled(false);
        JF_niños.Eliminar.setEnabled(false);
        JF_niños.Modificar.setEnabled(false);
        JF_niños.jButtonatras.setEnabled(false);
        JF_niños.jLabetxtniños.setText("ESCOJA ID PARA SELECCIONAR");
    }//GEN-LAST:event_jButtonjfniñosActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new JF_principal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_formacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_formacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_formacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_formacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_formacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButton4;
    public static javax.swing.JButton jButtoneliminar;
    public static javax.swing.JButton jButtonguardar;
    public static javax.swing.JButton jButtonjfgrado;
    public static javax.swing.JButton jButtonjfniños;
    public static javax.swing.JButton jButtonjfue;
    public static javax.swing.JButton jButtonmodificar;
    public static javax.swing.JButton jButtonnuevo;
    public static javax.swing.JButton jButtonseleccionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableFormacion;
    private javax.swing.JTextField jTextFieldIDF;
    public static javax.swing.JTextField jTextFieldIDGRADO;
    public static javax.swing.JTextField jTextFieldIDNIÑOS;
    public static javax.swing.JTextField jTextFieldIDUE;
    private javax.swing.JTextField jTextFieldTURNO;
    // End of variables declaration//GEN-END:variables
}
