/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package j_frame;

/**
 *
 * @author byvagner
 */
import clases.ingreso ;
public class JF_Ingreso extends javax.swing.JFrame {

    /**
     * Creates new form JF_Ingreso
     */
    ingreso i = new ingreso() ;
    
    public JF_Ingreso() {
        if(JF_Ingreso.OficialIngreso!=null){
            JF_Ingreso.OficialIngreso.dispose();
        }
        OficialIngreso = this ;
        initComponents();
        this.setLocationRelativeTo(null);
        i.MostrarJtableTI(jTableIngreso);
        this.LogearIngres();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public static JF_Ingreso OficialIngreso ;
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ID = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jTextFieldMonto = new javax.swing.JTextField();
        jTextFielFecha = new javax.swing.JTextField();
        jTextFieldDescripcion = new javax.swing.JTextField();
        jTextFieldCisecre = new javax.swing.JTextField();
        jTextFieldIDIngresooo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableIngreso = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jButtonNuevo = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonSeleccionar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jButtonSecretaria = new javax.swing.JButton();
        jButtonTipoIngreso = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ID.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Ingreso");
        ID.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        jLabel2.setText("Monto ");
        ID.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel3.setText("Fecha");
        ID.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel4.setText("Descripcion ");
        ID.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel5.setText("Personal ");
        ID.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel6.setText("ID");
        ID.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel7.setText("ID I.");
        ID.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));
        ID.add(jTextFieldID, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 40, -1));
        ID.add(jTextFieldMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 70, -1));
        ID.add(jTextFielFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 90, -1));
        ID.add(jTextFieldDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 110, -1));

        jTextFieldCisecre.setEditable(false);
        ID.add(jTextFieldCisecre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 80, -1));

        jTextFieldIDIngresooo.setEditable(false);
        ID.add(jTextFieldIDIngresooo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 60, -1));

        jTableIngreso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableIngreso);

        ID.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 710, 180));

        jLabel8.setText("Operaciones");
        ID.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, -1, -1));

        jButtonNuevo.setText("Nuevo ");
        jButtonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoActionPerformed(evt);
            }
        });
        ID.add(jButtonNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 90, 40));

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        ID.add(jButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 414, 100, 50));

        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });
        ID.add(jButtonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 100, 50));

        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        ID.add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, 100, 40));

        jButtonSeleccionar.setText("SELECCIONAR");
        jButtonSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeleccionarActionPerformed(evt);
            }
        });
        ID.add(jButtonSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 340, 120, -1));
        ID.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 1030, -1));
        ID.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 1050, -1));

        jButtonSecretaria.setText("Secretaria");
        jButtonSecretaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSecretariaActionPerformed(evt);
            }
        });
        ID.add(jButtonSecretaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 120, 30));

        jButtonTipoIngreso.setText("Tabla T Ingresos");
        jButtonTipoIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTipoIngresoActionPerformed(evt);
            }
        });
        ID.add(jButtonTipoIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 150, 30));

        jButton3.setText("ATRAS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        ID.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 520, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ID, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void limpiar (){
        jTextFieldID.setText("");
        jTextFieldMonto.setText("");
        jTextFielFecha.setText("");
        jTextFieldDescripcion.setText("");
        jTextFieldCisecre.setText("");
        jTextFieldIDIngresooo.setText("");
        
    }
    public void LogearIngres(){
        switch(JF_principal.valiladorPrincipal){
            case"1":
                JF_Ingreso.jButtonSecretaria.setEnabled(false);
                JF_Ingreso.jButtonTipoIngreso.setEnabled(false);
                JF_Ingreso.jButtonNuevo.setEnabled(false);
                JF_Ingreso.jButtonGuardar.setEnabled(false);
                JF_Ingreso.jButtonModificar.setEnabled(false);
                JF_Ingreso.jButtonEliminar.setEnabled(false);
                JF_Ingreso.jButtonSeleccionar.setEnabled(false);    
                break;
            case"2":
                break;
            case"3":
            case"4":
                JF_Ingreso.jButtonEliminar.setEnabled(false);
                break;
            default:
                break;               
        }
    }
    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        i.setIdI(jTextFieldID.getText());
        i.setMonto(jTextFieldMonto.getText());
        i.setFecha(jTextFielFecha.getText());
        i.setDescripcion(jTextFieldDescripcion.getText());
        i.setCisecre(jTextFieldCisecre.getText());
        i.setIdTipoIngreso(jTextFieldIDIngresooo.getText());
        
        i.guardar();
        i.MostrarJtableTI(jTableIngreso);
        this.limpiar();
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeleccionarActionPerformed
        // TODO add your handling code here:
        int fila =jTableIngreso.getSelectedRow();
        if (fila > -1){
            String idi = jTableIngreso.getValueAt(fila, 0).toString();
            String Monto = jTableIngreso.getValueAt(fila, 1).toString();
            String fecha = jTableIngreso.getValueAt(fila, 2).toString();
            String Descri = (jTableIngreso.getValueAt(fila, 3) != null) ? jTableIngreso.getValueAt(fila, 3).toString() : "";
            String ids = jTableIngreso.getValueAt(fila, 4).toString();
            String idti = jTableIngreso.getValueAt(fila, 5).toString();
            
            jTextFieldID.setText(idi);
            jTextFieldMonto.setText(Monto);
            jTextFielFecha.setText(fecha);
            jTextFieldDescripcion.setText(Descri);
            jTextFieldCisecre.setText(ids);
            jTextFieldIDIngresooo.setText(idti);
         
        }
    }//GEN-LAST:event_jButtonSeleccionarActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        i.setIdI(jTextFieldID.getText());
        i.setMonto(jTextFieldMonto.getText());
        i.setFecha(jTextFielFecha.getText());
        i.setDescripcion(jTextFieldDescripcion.getText());
        i.setCisecre(jTextFieldCisecre.getText());
        i.setIdTipoIngreso(jTextFieldIDIngresooo.getText());
        i.modificar();
        i.MostrarJtableTI(jTableIngreso);
        this.limpiar();
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        // TODO add your handling code here:
        i.setIdI(jTextFieldID.getText());
        i.eliminar();
        i.MostrarJtableTI(jTableIngreso);
        this.limpiar();
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonSecretariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSecretariaActionPerformed
        new JF_Secretaria().setVisible(true);
        JF_Secretaria.jButtonNuevo.setEnabled(false);
        JF_Secretaria.jButtonModificar.setEnabled(false);
        JF_Secretaria.jButtonguardar.setEnabled(false);
        JF_Secretaria.jButtonEliminar.setEnabled(false);
        JF_Secretaria.jButtonatras.setEnabled(false);
        JF_Secretaria.jButtonSeleccionar.setEnabled(false);
        JF_Secretaria.jLabelSecretaria.setText("ESCOGA UN ID PARA SELECCIONAR");
       
    }//GEN-LAST:event_jButtonSecretariaActionPerformed

    private void jButtonTipoIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTipoIngresoActionPerformed
       new JF_T_ingreso().setVisible(true);
       JF_T_ingreso.jButtonatras.setEnabled(false);
       JF_T_ingreso.jButtonNuevo.setEnabled(false);
       JF_T_ingreso.jButtonGuardar.setEnabled(false);
       JF_T_ingreso.jButtonModificar.setEnabled(false);
       JF_T_ingreso.jButtonEliminar.setEnabled(false);
       JF_T_ingreso.jButtonSeleccionar.setEnabled(false);
       JF_T_ingreso.jLabelTIPOiNGRESO.setText("ESCOGA UN ID PARA SELECCIONAR");
       
       
    }//GEN-LAST:event_jButtonTipoIngresoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       new JF_principal().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoActionPerformed
        this.limpiar();
    }//GEN-LAST:event_jButtonNuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Ingreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ID;
    public static javax.swing.JButton jButton3;
    public static javax.swing.JButton jButtonEliminar;
    public static javax.swing.JButton jButtonGuardar;
    public static javax.swing.JButton jButtonModificar;
    public static javax.swing.JButton jButtonNuevo;
    public static javax.swing.JButton jButtonSecretaria;
    public static javax.swing.JButton jButtonSeleccionar;
    public static javax.swing.JButton jButtonTipoIngreso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTableIngreso;
    private javax.swing.JTextField jTextFielFecha;
    public static javax.swing.JTextField jTextFieldCisecre;
    private javax.swing.JTextField jTextFieldDescripcion;
    private javax.swing.JTextField jTextFieldID;
    public static javax.swing.JTextField jTextFieldIDIngresooo;
    private javax.swing.JTextField jTextFieldMonto;
    // End of variables declaration//GEN-END:variables
}
