/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package j_frame;

/**
 *
 * @author byvagner
 */
import clases.labor;

public class JF_labor extends javax.swing.JFrame {

    /**
     * Creates new form JF_labor
     */
    labor l = new labor();
    
    public JF_labor() {
        if(JF_labor.OficialLabor!=null){
          JF_labor.OficialLabor.dispose();
        }
        OficialLabor = this ;
        initComponents();
        this.setLocationRelativeTo(null);
        l.Mostrar(jTablelabor);
        this.LogearLabor();
    }
    
    public static  JF_labor OficialLabor ;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablelabor = new javax.swing.JTable();
        jTextFieldFechaF = new javax.swing.JTextField();
        jTextFielDescripcion = new javax.swing.JTextField();
        jTextFieldIDarea = new javax.swing.JTextField();
        jTextFieldIDniños = new javax.swing.JTextField();
        jTextFieldFechaI = new javax.swing.JTextField();
        jTextFieldID = new javax.swing.JTextField();
        jTextFielciDencargado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButtonjfarea = new javax.swing.JButton();
        jButtonjfniños = new javax.swing.JButton();
        jButtonjfencargado = new javax.swing.JButton();
        jButtonNuevo = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonSeleccionar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("labor");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 40, -1));

        jTablelabor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablelabor);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 560, 230));
        jPanel1.add(jTextFieldFechaF, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 60, -1));
        jPanel1.add(jTextFielDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 70, -1));

        jTextFieldIDarea.setEditable(false);
        jTextFieldIDarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDareaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldIDarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 50, -1));

        jTextFieldIDniños.setEditable(false);
        jPanel1.add(jTextFieldIDniños, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 50, -1));
        jPanel1.add(jTextFieldFechaI, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 80, -1));
        jPanel1.add(jTextFieldID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 40, -1));

        jTextFielciDencargado.setEditable(false);
        jTextFielciDencargado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielciDencargadoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFielciDencargado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 60, -1));

        jLabel2.setText("fecha i");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel3.setText("fecha f");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel4.setText("descripcion");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel5.setText("id area");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel6.setText("id niños");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel7.setText("id");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel8.setText("ci Encargado");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jButtonjfarea.setText("tabla area");
        jButtonjfarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonjfareaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonjfarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 110, 30));

        jButtonjfniños.setText("tabla niños");
        jButtonjfniños.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonjfniñosActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonjfniños, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 120, 30));

        jButtonjfencargado.setText("Buscar Encargado");
        jButtonjfencargado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonjfencargadoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonjfencargado, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 160, 30));

        jButtonNuevo.setText("nuevo");
        jButtonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 80, -1));

        jButtonGuardar.setText("guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 100, -1));

        jButtonModificar.setText("modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 90, -1));

        jButtonEliminar.setText("eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 90, -1));

        jButtonSeleccionar.setText("SELECCIONAR ");
        jButtonSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeleccionarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, 170, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 840, -1));

        jButton9.setText("ATRAS");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 440, 100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 958, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldIDareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDareaActionPerformed

    private void jTextFielciDencargadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielciDencargadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielciDencargadoActionPerformed
    public void limpiar (){
        jTextFieldID.setText("");
        jTextFieldFechaI.setText("");
        jTextFieldFechaF.setText("");
        jTextFielDescripcion.setText("");
        jTextFieldIDarea.setText("");
        jTextFielciDencargado.setText("");
        jTextFieldIDniños.setText("");
    }
    public void LogearLabor(){
        switch(JF_principal.valiladorPrincipal){
            case"1":
                JF_labor.jButtonjfarea.setEnabled(false);
                JF_labor.jButtonjfniños.setEnabled(false);
                JF_labor.jButtonjfencargado.setEnabled(false);
                JF_labor.jButtonNuevo.setEnabled(false);
                JF_labor.jButtonGuardar.setEnabled(false);
                JF_labor.jButtonModificar.setEnabled(false);
                JF_labor.jButtonEliminar.setEnabled(false);
                JF_labor.jButtonSeleccionar.setEnabled(false);
                break;
            case"2":
                break;
            case"3":
            case"4":
                JF_labor.jButtonEliminar.setEnabled(false);
                break;
            default:
                break;               
        }
    }
    private void jButtonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoActionPerformed
        // TODO add your handling code here:
        this.limpiar();
       
    }//GEN-LAST:event_jButtonNuevoActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
        l.setIdL(jTextFieldID.getText());
        l.setFecha_i(jTextFieldFechaI.getText());
        l.setFecha_F(jTextFieldFechaF.getText());
        l.setDescripcion(jTextFielDescripcion.getText());
        l.setIdarea(jTextFieldIDarea.getText());
        l.setIdniños(jTextFieldIDniños.getText());
        l.setCienc(jTextFielciDencargado.getText());
        l.guardar();
        l.Mostrar(jTablelabor);
        this.limpiar();
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        // TODO add your handling code here:
        l.setIdL(jTextFieldID.getText());
        l.setFecha_i(jTextFieldFechaI.getText());
        l.setFecha_F(jTextFieldFechaF.getText());
        l.setDescripcion(jTextFielDescripcion.getText());
        l.setIdarea(jTextFieldIDarea.getText());
        l.setIdniños(jTextFieldIDniños.getText());
        l.setCienc(jTextFielciDencargado.getText());
        l.modificar();
        l.Mostrar(jTablelabor);
        this.limpiar();
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        // TODO add your handling code here:
        l.setIdL(jTextFieldID.getText());
        l.eliminar();
        l.Mostrar(jTablelabor);
        this.limpiar();
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeleccionarActionPerformed
        // TODO add your handling code here:
        int fila =jTablelabor.getSelectedRow();
        if (fila > -1){
            String idP = jTablelabor.getValueAt(fila, 0).toString();
            String fecha_i = jTablelabor.getValueAt(fila, 1).toString();
            String fecha_f = (jTablelabor.getValueAt(fila, 2) != null) ? jTablelabor.getValueAt(fila, 2).toString() : "";
            String descripcion = jTablelabor.getValueAt(fila, 3).toString();
            String idarea = jTablelabor.getValueAt(fila, 4).toString();
            String idniños = jTablelabor.getValueAt(fila, 5).toString();
            String idencargado = jTablelabor.getValueAt(fila, 6).toString();
           
            jTextFieldID.setText(idP);
            jTextFieldFechaI.setText(fecha_i);
            jTextFieldFechaF.setText(fecha_f);
            jTextFielDescripcion.setText(descripcion);
            jTextFieldIDarea.setText(idarea);
            jTextFieldIDniños.setText(idniños);
            jTextFielciDencargado.setText(idencargado);
        }
    }//GEN-LAST:event_jButtonSeleccionarActionPerformed

    private void jButtonjfareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonjfareaActionPerformed
        new JF_area().setVisible(true);
        JF_area.jButtonuevo.setEnabled(false);
        JF_area.jButtonGuardar.setEnabled(false);
        JF_area.jButtonmodificar.setEnabled(false);
        JF_area.jButtonEliminar.setEnabled(false);
        JF_area.jButtonSeleccionar.setEnabled(false);
        JF_area.jButton2.setEnabled(false);
        JF_area.jButtonuevo.setEnabled(false);
        JF_area.jLabeltxtarea.setText("ESCOJA EL ID PARA SELECCIONAR");
        
    }//GEN-LAST:event_jButtonjfareaActionPerformed

    private void jButtonjfniñosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonjfniñosActionPerformed
        new JF_niños().setVisible(true);
        JF_niños.Tutor.setEnabled(false);
        JF_niños.jButtonPersonal.setEnabled(false);
        JF_niños.Nuevo.setEnabled(false);
        JF_niños.Guardar.setEnabled(false);
        JF_niños.Eliminar.setEnabled(false);
        JF_niños.Modificar.setEnabled(false);
        JF_niños.jButtonseleccionar.setEnabled(false);
        JF_niños.jButtonatras.setEnabled(false);
        JF_niños.jLabetxtniños.setText("BUSQUE UN ID PARA SELECCIONAR");  
    }//GEN-LAST:event_jButtonjfniñosActionPerformed

    private void jButtonjfencargadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonjfencargadoActionPerformed
       new JF_Encargado().setVisible(true);
       JF_Encargado.jButtonNuevoE.setEnabled(false);
       JF_Encargado.jButtonModificarE.setEnabled(false);
       JF_Encargado.jButtonguardarE.setEnabled(false);
       JF_Encargado.jButtonEliminarE.setEnabled(false);
       JF_Encargado.jButtonSeleccionar.setEnabled(false);
       JF_Encargado.jButton2.setEnabled(false);
       JF_Encargado.jLabeltxtencargado.setText("ESCOJA UN ID PARA SELECCIONAR");
    }//GEN-LAST:event_jButtonjfencargadoActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        new JF_principal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_labor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_labor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_labor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_labor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_labor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButton9;
    public static javax.swing.JButton jButtonEliminar;
    public static javax.swing.JButton jButtonGuardar;
    public static javax.swing.JButton jButtonModificar;
    public static javax.swing.JButton jButtonNuevo;
    public static javax.swing.JButton jButtonSeleccionar;
    public static javax.swing.JButton jButtonjfarea;
    public static javax.swing.JButton jButtonjfencargado;
    public static javax.swing.JButton jButtonjfniños;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTablelabor;
    private javax.swing.JTextField jTextFielDescripcion;
    public static javax.swing.JTextField jTextFielciDencargado;
    private javax.swing.JTextField jTextFieldFechaF;
    private javax.swing.JTextField jTextFieldFechaI;
    private javax.swing.JTextField jTextFieldID;
    public static javax.swing.JTextField jTextFieldIDarea;
    public static javax.swing.JTextField jTextFieldIDniños;
    // End of variables declaration//GEN-END:variables
}
