/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package j_frame;

import clases.*;
import static j_frame.JF_login.txtpassword;
import static j_frame.JF_login.txtuser;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author byvagner
 */
public class JF_principal extends javax.swing.JFrame {
    
    /**
     * Creates new form JF_principal
     */
    //valores static para todos los jframes .
     public static JF_Ingreso ingreso ;
     public static JF_Personal personal ;
     public static JF_T_ingreso T_ingreso ;
     public static  JF_UE ue ;
     public static JF_area area ;
     public static JF_formacion formacion ;
     public static JF_grado grado ;
     public static JF_labor labor ;
     public static JF_login login ;
     public static JF_niños niños ;
     public static JF_operaciones operaciones ;
     public static JF_principal principal ;
     public static JF_tutor tutor ;
     public static JF_usuario usuario ;
     public static JF_PrincipalPersonal ppersonal ;
     public static JF_Secretaria secretaria ;
     public static JF_Encargado encargado ;
     public static JF_Administrador administrador ;
     public static JF_Directora directora ;
   
     usuario usu = new usuario();
     
  
     
    public JF_principal() {
        initComponents();
    customizeButton(jButton1);
    customizeButton(jButtonCrearUsuario);
    customizeButton(jButtonFormacion);
    customizeButton(jButtonGestionarGrado);
    customizeButton(jButtonGestionarTipoIngreso);
    customizeButton(jButtonGestionararea);
    customizeButton(jButtonGestionarue);
    customizeButton(jButtonIngresos);
    customizeButton(jButtonLabor);
    customizeButton(jButtonNiños);
    customizeButton(jButtonPersonal);
    customizeButton(jButtontutor);
    customizeButton(jButtonusuariGestionarPersonal);
        this.setLocationRelativeTo(null);
        this.Logear();
        System.out.println("->"+valiladorPrincipal);
    }
    
    
    public static String valiladorPrincipal ; // se guardar el id
    
// que va donde sea 
    /**  
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelID = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonNiños = new javax.swing.JButton();
        jButtonusuariGestionarPersonal = new javax.swing.JButton();
        jButtonLabor = new javax.swing.JButton();
        jButtonIngresos = new javax.swing.JButton();
        jButtonFormacion = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelTipo = new javax.swing.JLabel();
        jLabelCorreo = new javax.swing.JLabel();
        jButtonCrearUsuario = new javax.swing.JButton();
        jLabelDirectora = new javax.swing.JLabel();
        jButtontutor = new javax.swing.JButton();
        jButtonGestionararea = new javax.swing.JButton();
        jButtonGestionarTipoIngreso = new javax.swing.JButton();
        jButtonGestionarGrado = new javax.swing.JButton();
        jButtonGestionarue = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonPersonal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabelID.setText("Ci");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonNiños.setText("Ver niños");
        jButtonNiños.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNiñosActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNiños, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 150, -1));

        jButtonusuariGestionarPersonal.setText("Gestionar Personal ");
        jButtonusuariGestionarPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonusuariGestionarPersonalActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonusuariGestionarPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 180, -1));

        jButtonLabor.setText("Ver labores");
        jButtonLabor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLaborActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLabor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 150, -1));

        jButtonIngresos.setText("Ver Ingresos");
        jButtonIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresosActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonIngresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 150, -1));

        jButtonFormacion.setText("Ver Formacion ");
        jButtonFormacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFormacionActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonFormacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 150, -1));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 20, 600));

        jButton1.setText("volver ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 540, 100, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setText("Personal Ingresado :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, -1, -1));

        jLabelNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(0, 0, 51));
        jLabelNombre.setText("nombre");
        jPanel1.add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 510, -1, -1));

        jLabelTipo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTipo.setForeground(new java.awt.Color(0, 0, 51));
        jLabelTipo.setText("tipo");
        jPanel1.add(jLabelTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 510, -1, -1));

        jLabelCorreo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelCorreo.setForeground(new java.awt.Color(0, 0, 51));
        jLabelCorreo.setText("correo");
        jPanel1.add(jLabelCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 510, -1, -1));

        jButtonCrearUsuario.setText("Crear Usuario");
        jButtonCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCrearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 140, 30));

        jLabelDirectora.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelDirectora.setForeground(new java.awt.Color(0, 0, 102));
        jLabelDirectora.setText("BIENVENIDO!");
        jPanel1.add(jLabelDirectora, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 200, 50));

        jButtontutor.setText("Ver tutor");
        jButtontutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtontutorActionPerformed(evt);
            }
        });
        jPanel1.add(jButtontutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 150, -1));

        jButtonGestionararea.setText("Gestionar area");
        jButtonGestionararea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGestionarareaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonGestionararea, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 180, -1));

        jButtonGestionarTipoIngreso.setText("Gestionar Tipo Ingresos");
        jButtonGestionarTipoIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGestionarTipoIngresoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonGestionarTipoIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 180, -1));

        jButtonGestionarGrado.setText("Gestionar Grado");
        jButtonGestionarGrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGestionarGradoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonGestionarGrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 180, -1));

        jButtonGestionarue.setText("Gestionar Unidad Educativa");
        jButtonGestionarue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGestionarueActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonGestionarue, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 180, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 1000, -1));

        jButtonPersonal.setText("Ver Personal");
        jButtonPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPersonalActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 150, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/7.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 440, 330));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/6.jpeg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 992, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
   
   public void Logear(){
       switch(valiladorPrincipal){
           case "1": //directora
               this.LoginDirectora();
               principal.jButtonCrearUsuario.setVisible(false);
               principal.jButtonGestionararea.setEnabled(false);
               principal.jButtonusuariGestionarPersonal.setEnabled(false);
               principal.jButtonGestionarTipoIngreso.setEnabled(false);
               principal.jButtonGestionarGrado.setEnabled(false);
               principal.jButtonGestionarue.setEnabled(false);   
               break;
            case"2":
                this.LoginAdm();
                break;
            case"3":
            case"4":
                this.LoginSecretarias();
                principal.jButtonCrearUsuario.setEnabled(false);
                break;
           default:
               break;
       }
   }
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   public void LoginDirectora(){
       //los jlabel 
       usu.validarUserLogeado(valiladorPrincipal, principal.jLabelID, principal.jLabelNombre, principal.jLabelTipo, principal.jLabelCorreo);

   }
   public void LoginAdm(){
       usu.validarUserLogeado(valiladorPrincipal, principal.jLabelID, principal.jLabelNombre, principal.jLabelTipo, principal.jLabelCorreo);
   }
   public void LoginSecretarias(){
       usu.validarUserLogeado(valiladorPrincipal, principal.jLabelID, principal.jLabelNombre, principal.jLabelTipo, principal.jLabelCorreo);
   }
   
   private void customizeButton(JButton button) {
    button.setPreferredSize(new Dimension(200, 50));
    button.setFocusPainted(false);
    button.setBorderPainted(false);
    button.setContentAreaFilled(false);
    button.setOpaque(true); // Fondo no transparente

    // Colores más fuertes
    Color normalColor = new Color(100, 149, 237); // Azul claro fuerte
    Color hoverColor = new Color(70, 130, 180); // Azul intermedio
    Color pressColor = new Color(30, 60, 120); // Azul oscuro

    // Establece el color inicial del fondo
    button.setBackground(normalColor);
    button.setForeground(Color.WHITE); // Texto en blanco
    button.setFont(new Font("Arial", Font.BOLD, 16));

    // Bordes redondeados usando 'setBorder' directamente
    button.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0), 2)); // Borde negro

    // Agregar efectos de cambio de color y sombra
    button.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            // Efecto de cambio de color suave
            button.setBackground(hoverColor); // Color cuando el cursor entra
            button.setCursor(new Cursor(Cursor.HAND_CURSOR)); // Cambia el cursor

            // Sombra dinámica
            button.setBorder(BorderFactory.createLineBorder(new Color(50, 50, 50), 3)); // Cambia el borde a más grueso
        }

        @Override
        public void mouseExited(java.awt.event.MouseEvent evt) {
            button.setBackground(normalColor); // Vuelve al color normal
            button.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0), 2)); // Vuelve al borde normal
        }

        @Override
        public void mousePressed(java.awt.event.MouseEvent evt) {
            button.setBackground(pressColor); // Color cuando se presiona
        }

        @Override
        public void mouseReleased(java.awt.event.MouseEvent evt) {
            button.setBackground(hoverColor); // Vuelve al color de hover después de soltar
        }
    });
}

   
   
   
   
    private void jButtonNiñosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNiñosActionPerformed

        new JF_niños().setVisible(true);
        JF_niños.jButtonseleccionarId.setEnabled(false);
        this.dispose();
    }//GEN-LAST:event_jButtonNiñosActionPerformed
   
    private void jButtonLaborActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLaborActionPerformed
        // TODO add your handling code here:
        new JF_labor().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonLaborActionPerformed

    private void jButtonIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresosActionPerformed
        // TODO add your handling code here:
        new JF_Ingreso().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonIngresosActionPerformed

    private void jButtonFormacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFormacionActionPerformed
        // TODO add your handling code here:
       new JF_formacion().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButtonFormacionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        String [] arreglo = {"Si","NO , SALIR"};
        int opcion = JOptionPane.showOptionDialog(null, "¿ QUIERES INGRESAR DE NUEVO ?", "Elige..", WIDTH, JOptionPane.QUESTION_MESSAGE, null, arreglo, "");
        String valor1 = "Si" ;
        if (arreglo[opcion]==valor1){
            this.dispose();
            new JF_login().setVisible(true);
     
        }else{
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearUsuarioActionPerformed
        new JF_usuario().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCrearUsuarioActionPerformed

    private void jButtontutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtontutorActionPerformed
        new JF_tutor().setVisible(true);
        JF_tutor.jButtonSeleID.setEnabled(false);
        this.dispose();
    }//GEN-LAST:event_jButtontutorActionPerformed

    private void jButtonusuariGestionarPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonusuariGestionarPersonalActionPerformed
        // TODO add your handling code here:
        new JF_PrincipalPersonal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonusuariGestionarPersonalActionPerformed

    private void jButtonGestionarareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGestionarareaActionPerformed
        // TODO add your handling code here:
        new JF_area().setVisible(true);
        JF_area.jButton1.setEnabled(false);
        this.dispose();
    }//GEN-LAST:event_jButtonGestionarareaActionPerformed

    private void jButtonGestionarTipoIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGestionarTipoIngresoActionPerformed
        // TODO add your handling code here:
        new JF_T_ingreso().setVisible(true);
        JF_T_ingreso.jButtonSeleccionarID.setEnabled(false);
        this.dispose();
    }//GEN-LAST:event_jButtonGestionarTipoIngresoActionPerformed

    private void jButtonGestionarGradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGestionarGradoActionPerformed
        // TODO add your handling code here:
        new JF_grado().setVisible(true);
        JF_grado.jButtonSeleccionaID.setEnabled(false);
        this.dispose();
    }//GEN-LAST:event_jButtonGestionarGradoActionPerformed

    private void jButtonGestionarueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGestionarueActionPerformed
        // TODO add your handling code here:
        new JF_UE().setVisible(true);
        JF_UE.jButtonseleID.setEnabled(false);
        this.dispose();
    }//GEN-LAST:event_jButtonGestionarueActionPerformed

    private void jButtonPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPersonalActionPerformed
        // TODO add your handling code here:
        new JF_Personal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonPersonalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    public static javax.swing.JButton jButtonCrearUsuario;
    private javax.swing.JButton jButtonFormacion;
    public static javax.swing.JButton jButtonGestionarGrado;
    public static javax.swing.JButton jButtonGestionarTipoIngreso;
    public static javax.swing.JButton jButtonGestionararea;
    public static javax.swing.JButton jButtonGestionarue;
    private javax.swing.JButton jButtonIngresos;
    private javax.swing.JButton jButtonLabor;
    private javax.swing.JButton jButtonNiños;
    private javax.swing.JButton jButtonPersonal;
    private javax.swing.JButton jButtontutor;
    public static javax.swing.JButton jButtonusuariGestionarPersonal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabelCorreo;
    public static javax.swing.JLabel jLabelDirectora;
    public static javax.swing.JLabel jLabelID;
    public static javax.swing.JLabel jLabelNombre;
    public static javax.swing.JLabel jLabelTipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
