/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package j_frame;

/**
 *
 * @author byvagner
 */
import clases.usuario;
import static j_frame.JF_login.txtpassword;
import static j_frame.JF_login.txtuser;

public class JF_PrincipalPersonal extends javax.swing.JFrame {

    /**
     * Creates new form JF_PrincipalPersonal
     */
    usuario u = new usuario();
    String user = txtuser.getText();
     String password = String.valueOf(txtpassword.getPassword());
     String resul = u.validarUser(user, password);
     
    public JF_PrincipalPersonal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.LogearPP();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonEncargado = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jButtonDirectora = new javax.swing.JButton();
        jButtonADM = new javax.swing.JButton();
        jButtonSecretaria = new javax.swing.JButton();
        jButtonatras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Personal ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        jButtonEncargado.setText("Encargado");
        jButtonEncargado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEncargadoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEncargado, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, 160, 70));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 890, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 492, 900, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 900, -1));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, -1, -1));

        jButtonDirectora.setText("Directora");
        jButtonDirectora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDirectoraActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDirectora, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 170, 70));

        jButtonADM.setText("administrador del Sistema");
        jButtonADM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonADMActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonADM, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 370, 200, 70));

        jButtonSecretaria.setText("Secretaria ");
        jButtonSecretaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSecretariaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSecretaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 170, 70));

        jButtonatras.setText("atras");
        jButtonatras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonatrasActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonatras, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 520, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void LogearPP(){
        switch(JF_principal.valiladorPrincipal){
            case"1":
                break;
            case"2":
                break;
            case"3":
            case"4":
                JF_PrincipalPersonal.jButtonSecretaria.setEnabled(false);
                JF_PrincipalPersonal.jButtonDirectora.setEnabled(false);
                JF_PrincipalPersonal.jButtonADM.setEnabled(false);
                break;
            default:
                break;               
        }
    }
    private void jButtonSecretariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSecretariaActionPerformed
        new JF_Secretaria().setVisible(true);
        JF_Secretaria.jButtonSeleccionarId.setEnabled(false);
        this.dispose();
    }//GEN-LAST:event_jButtonSecretariaActionPerformed

    private void jButtonEncargadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEncargadoActionPerformed
        new JF_Encargado().setVisible(true);
        JF_Encargado.jButtonSeleccionarId.setEnabled(false);
        this.dispose();
    }//GEN-LAST:event_jButtonEncargadoActionPerformed

    private void jButtonDirectoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDirectoraActionPerformed
        new JF_Directora().setVisible(true);
        JF_Directora.jButtonSeleccionarId.setEnabled(false);
        this.dispose();
    }//GEN-LAST:event_jButtonDirectoraActionPerformed

    private void jButtonADMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonADMActionPerformed
        new JF_Administrador().setVisible(true);
        JF_Administrador.jButtonSeleccionarId.setEnabled(false);
        this.dispose();
    }//GEN-LAST:event_jButtonADMActionPerformed

    private void jButtonatrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonatrasActionPerformed
        new JF_principal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonatrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_PrincipalPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_PrincipalPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_PrincipalPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_PrincipalPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_PrincipalPersonal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButtonADM;
    public static javax.swing.JButton jButtonDirectora;
    public static javax.swing.JButton jButtonEncargado;
    public static javax.swing.JButton jButtonSecretaria;
    private javax.swing.JButton jButtonatras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
