/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package j_frame;

import clases.Personal;

/**
 *
 * @author byvagner
 */
public class JF_Personal extends javax.swing.JFrame {
  
    /**
     * Creates new form JF_Personal
     */
    Personal p = new Personal();
    
    public JF_Personal() {
        initComponents();
        this.setLocationRelativeTo(null);
        p.MostrarPersonal(Tabla_Personal);
        this.LogearPersonal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jt_Tipo = new javax.swing.JTextField();
        jt_Apellido = new javax.swing.JTextField();
        jt_sexo = new javax.swing.JTextField();
        jt_ci = new javax.swing.JTextField();
        jt_correo = new javax.swing.JTextField();
        jt_cel = new javax.swing.JTextField();
        jt_ff = new javax.swing.JTextField();
        jt_nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jt_fi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Personal = new javax.swing.JTable();
        jButtonEliminar = new javax.swing.JButton();
        jButtonNuevo = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jButtonSeleccionar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButtonatras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Personal");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 110, 60));
        jPanel1.add(jt_Tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 100, -1));
        jPanel1.add(jt_Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 100, -1));
        jPanel1.add(jt_sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 30, -1));
        jPanel1.add(jt_ci, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 40, -1));
        jPanel1.add(jt_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 130, -1));
        jPanel1.add(jt_cel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 110, -1));
        jPanel1.add(jt_ff, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 100, -1));

        jt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_nombreActionPerformed(evt);
            }
        });
        jPanel1.add(jt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 100, -1));

        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 50, -1));

        jLabel3.setText("Apellido");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 50, -1));

        jLabel4.setText("Sexo");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 50, -1));

        jLabel5.setText("Tipo");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 50, -1));

        jLabel6.setText("Correo");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 50, -1));

        jLabel7.setText("cel");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 50, -1));

        jLabel8.setText("fecha Final ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 70, -1));

        jLabel9.setText("Ci");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 50, -1));

        jLabel10.setText("fecha Inico ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 70, -1));

        jt_fi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_fiActionPerformed(evt);
            }
        });
        jPanel1.add(jt_fi, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 110, -1));

        Tabla_Personal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Apellido", "Sexo", "Tipo", "Correo", "phone", "F Inico ", "F FInal"
            }
        ));
        jScrollPane1.setViewportView(Tabla_Personal);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 830, 320));

        jButtonEliminar.setText("Eliminar ");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, 90, -1));

        jButtonNuevo.setText("Nuevo");
        jButtonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 100, -1));

        jButtonModificar.setText("Modificar ");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, 90, -1));

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 90, -1));

        jButtonSeleccionar.setText("SELECCIONAR");
        jButtonSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeleccionarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 440, 120, -1));

        jLabel11.setText("Operaciones ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, -1, 20));

        jButton1.setText("SELECCIONAR CI ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 440, 140, -1));

        jButtonatras.setText("Atras");
        jButtonatras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonatrasActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonatras, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 520, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_nombreActionPerformed
    public void limpiar (){
        jt_ci.setText("");
        jt_nombre.setText("");
        jt_Apellido.setText("");
        jt_Tipo.setText("");
        jt_correo.setText("");
        jt_cel.setText("");
        jt_sexo.setText("");
        jt_fi.setText("");
        jt_ff.setText("");
    }
    public void LogearPersonal(){
        switch(JF_principal.valiladorPrincipal){
            case"1":
                JF_Personal.jButtonNuevo.setVisible(false);
                JF_Personal.jButtonGuardar.setVisible(false);
                JF_Personal.jButtonEliminar.setVisible(false);
                JF_Personal.jButtonModificar.setVisible(false);
                JF_Personal.jButtonSeleccionar.setVisible(false);
                JF_Personal.jButton1.setVisible(false);
                break;
            case"2":
                JF_Personal.jButtonNuevo.setVisible(false);
                JF_Personal.jButtonGuardar.setVisible(false);
                JF_Personal.jButtonEliminar.setVisible(false);
                JF_Personal.jButtonModificar.setVisible(false);
                JF_Personal.jButtonSeleccionar.setVisible(false);
                JF_Personal.jButton1.setVisible(false);
                break;
            case"3":
            case"4":
                JF_Personal.jButtonNuevo.setVisible(false);
                JF_Personal.jButtonGuardar.setVisible(false);
                JF_Personal.jButtonEliminar.setVisible(false);
                JF_Personal.jButtonModificar.setVisible(false);
                JF_Personal.jButtonSeleccionar.setVisible(false);
                JF_Personal.jButton1.setVisible(false);
                break;
            default:
                break;               
        }
    }
    private void jButtonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoActionPerformed
         jt_ci.setText("");
         jt_nombre.setText("");
         jt_Apellido.setText("");
         jt_Tipo.setText("");
         jt_correo.setText("");
         jt_cel.setText("");
         jt_sexo.setText("");
         jt_fi.setText("");
         jt_ff.setText("");
    }//GEN-LAST:event_jButtonNuevoActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        p.setCi(jt_ci.getText());
        p.setNombre(jt_nombre.getText());
        p.setApellido(jt_Apellido.getText());
        p.setSexo(jt_sexo.getText());
        p.setCorreo(jt_correo.getText());
        p.setTipo(jt_Tipo.getText());
        p.setCel_ref(jt_cel.getText());
        p.setFecha_i(jt_fi.getText());
        p.setFEcha_f(jt_ff.getText());
        
        p.InsertarPersonal();
        
        p.MostrarPersonal(Tabla_Personal);
        this.limpiar();
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jt_fiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_fiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_fiActionPerformed

    private void jButtonSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeleccionarActionPerformed
        
        int fila =Tabla_Personal.getSelectedRow();
        if (fila > -1){
            String idP = Tabla_Personal.getValueAt(fila, 0).toString();
            String Nombre = Tabla_Personal.getValueAt(fila, 1).toString();
            String Apellido = Tabla_Personal.getValueAt(fila, 2).toString();
            String sexo = Tabla_Personal.getValueAt(fila, 3).toString();
            String Tipo = Tabla_Personal.getValueAt(fila, 4).toString();
            String correo = Tabla_Personal.getValueAt(fila, 5).toString();
            String cel_ref = Tabla_Personal.getValueAt(fila, 6).toString();
            String Fecha_i = Tabla_Personal.getValueAt(fila, 7).toString();
            String fecha_f = Tabla_Personal.getValueAt(fila, 8).toString()!= null ? Tabla_Personal.getValueAt(fila, 8).toString() : "";
            
            jt_ci.setText(idP);
            jt_nombre.setText(Nombre);
            jt_Apellido.setText(Apellido);
            jt_sexo.setText(sexo);
            jt_Tipo.setText(Tipo);
            jt_correo.setText(correo);
            jt_cel.setText(cel_ref);
            jt_fi.setText(Fecha_i);
            jt_ff.setText(fecha_f);
        }
    }//GEN-LAST:event_jButtonSeleccionarActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        p.setCi(jt_ci.getText());
        p.setNombre(jt_nombre.getText());
        p.setApellido(jt_Apellido.getText());
        p.setSexo(jt_sexo.getText());
        p.setTipo(jt_Tipo.getText());
        p.setCorreo(jt_correo.getText());
        p.setCel_ref(jt_cel.getText());
        p.setFecha_i(jt_fi.getText());
        p.setFEcha_f(jt_ff.getText());
        p.ModificarPersonal();
        p.MostrarPersonal(Tabla_Personal);
        this.limpiar();
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        p.setCi(jt_ci.getText());
        p.EliminarPersonal();
        p.MostrarPersonal(Tabla_Personal);
        this.limpiar();
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int fila =Tabla_Personal.getSelectedRow();
        if (fila > -1){
           String id = Tabla_Personal.getValueAt(fila, 0).toString();
           if (JF_usuario.OficialUsu != null && JF_usuario.OficialUsu.isVisible()) {
           JF_usuario.OficialUsu.jTextFieldIDPERSONAL.setText(id);
           JF_Personal.jButtonNuevo.setEnabled(true);
           JF_Personal.jButtonGuardar.setEnabled(true);
           JF_Personal.jButtonEliminar.setEnabled(true);
           JF_Personal.jButtonModificar.setEnabled(true);
           JF_Personal.jButtonSeleccionar.setEnabled(true);
           JF_Personal.jButtonatras.setEnabled(true);
           JF_Personal.jButton1.setVisible(false);
           }
        }
         this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonatrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonatrasActionPerformed
       new JF_principal().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButtonatrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla_Personal;
    public static javax.swing.JButton jButton1;
    public static javax.swing.JButton jButtonEliminar;
    public static javax.swing.JButton jButtonGuardar;
    public static javax.swing.JButton jButtonModificar;
    public static javax.swing.JButton jButtonNuevo;
    public static javax.swing.JButton jButtonSeleccionar;
    public static javax.swing.JButton jButtonatras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jt_Apellido;
    private javax.swing.JTextField jt_Tipo;
    private javax.swing.JTextField jt_cel;
    private javax.swing.JTextField jt_ci;
    private javax.swing.JTextField jt_correo;
    private javax.swing.JTextField jt_ff;
    private javax.swing.JTextField jt_fi;
    private javax.swing.JTextField jt_nombre;
    private javax.swing.JTextField jt_sexo;
    // End of variables declaration//GEN-END:variables
}
