/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package j_frame;

/**
 *
 * @author byvagner
 */
import clases.Secretaria;

public class JF_Secretaria extends javax.swing.JFrame {

    /**
     * Creates new form JF_Secretaria
     */
    
    Secretaria s = new Secretaria();
    
    public JF_Secretaria() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        s.MostrarSecre(jTablesECRETARIA);
        this.verficar();
        this.LogearSecre();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldNOMBRE = new javax.swing.JTextField();
        jTextFieldAPELLIDO = new javax.swing.JTextField();
        jTextFieldSEXO = new javax.swing.JTextField();
        jTextFieldTIPO = new javax.swing.JTextField();
        jTextFieldCORREO = new javax.swing.JTextField();
        jTextFieldCELULAR = new javax.swing.JTextField();
        jTextFieldFECHA_I = new javax.swing.JTextField();
        jTextFieldFECHA_F = new javax.swing.JTextField();
        jTextFielVELOCIDAD_T = new javax.swing.JTextField();
        jTextFielCI = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablesECRETARIA = new javax.swing.JTable();
        jButtonNuevo = new javax.swing.JButton();
        jButtonguardar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonSeleccionar = new javax.swing.JButton();
        jButtonSeleccionarId = new javax.swing.JButton();
        jButtonatras = new javax.swing.JButton();
        jLabelSecretaria = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Secretaria ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 60, -1));

        jLabel2.setText("APELLIDO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel3.setText("SEXO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jLabel4.setText("CI");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        jLabel5.setText("TIPO");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        jLabel6.setText("CORREO");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, -1, -1));

        jLabel7.setText("CELULAR");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, -1, -1));

        jLabel8.setText("FEHCA INICO");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, -1, -1));

        jLabel9.setText("FECHA FINAL");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, -1, -1));

        jLabel10.setText("NOMBRE");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        jLabel11.setText("VELOCIDAD T.");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, -1, -1));
        jPanel1.add(jTextFieldNOMBRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 190, -1));
        jPanel1.add(jTextFieldAPELLIDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 190, -1));
        jPanel1.add(jTextFieldSEXO, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 210, -1));

        jTextFieldTIPO.setEditable(false);
        jTextFieldTIPO.setText("Secretaria");
        jTextFieldTIPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTIPOActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldTIPO, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 210, -1));
        jPanel1.add(jTextFieldCORREO, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 190, -1));
        jPanel1.add(jTextFieldCELULAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 190, -1));
        jPanel1.add(jTextFieldFECHA_I, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 170, -1));
        jPanel1.add(jTextFieldFECHA_F, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 170, -1));
        jPanel1.add(jTextFielVELOCIDAD_T, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 170, -1));
        jPanel1.add(jTextFielCI, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 220, -1));

        jTablesECRETARIA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablesECRETARIA);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 940, 100));

        jButtonNuevo.setText("nuevo");
        jButtonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, 70, -1));

        jButtonguardar.setText("guardar");
        jButtonguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonguardarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, 70, -1));

        jButtonModificar.setText("modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 120, 80, -1));

        jButtonEliminar.setText("eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 170, 80, -1));

        jButtonSeleccionar.setText("seleccionar");
        jButtonSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeleccionarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 464, 110, 30));

        jButtonSeleccionarId.setText("Seleccionar ID ");
        jButtonSeleccionarId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeleccionarIdActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSeleccionarId, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 464, 120, 30));

        jButtonatras.setText("Atras");
        jButtonatras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonatrasActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonatras, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 280, 70, -1));
        jPanel1.add(jLabelSecretaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 470, 240, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 993, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void limpiar(){
        jTextFielCI.setText("");
        jTextFieldNOMBRE.setText("");
        jTextFieldAPELLIDO.setText("");
        jTextFieldSEXO.setText("");
        //jTextFieldTIPO.setText("");
        jTextFieldCORREO.setText("");
        jTextFieldCELULAR.setText("");
        jTextFieldFECHA_I.setText("");
        jTextFieldFECHA_F.setText("");
        jTextFielVELOCIDAD_T.setText("");
        
    }
    public void verficar(){
        if (JF_principal.niños != null && JF_principal.niños.isVisible()) {
            JF_principal.secretaria.jButtonSeleccionarId.setEnabled(true);
        }
    }
    public void LogearSecre(){
        switch(JF_principal.valiladorPrincipal){
            case"1":
                JF_Secretaria.jButtonNuevo.setEnabled(false);
                JF_Secretaria.jButtonModificar.setEnabled(false);
                JF_Secretaria.jButtonguardar.setEnabled(false);
                JF_Secretaria.jButtonEliminar.setEnabled(false);
                JF_Secretaria.jButtonSeleccionarId.setEnabled(false);
                JF_Secretaria.jButtonSeleccionar.setEnabled(false); 
                break;
            case"2":
                break;
            case"3":
            case"4":   
                JF_Secretaria.jButtonEliminar.setEnabled(false);
                break;
                
            default:
                break;
        }
    }
    private void jButtonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoActionPerformed
        // TODO add your handling code here:
        this.limpiar();
    }//GEN-LAST:event_jButtonNuevoActionPerformed

    private void jButtonguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonguardarActionPerformed
        // TODO add your handling code here:
        s.setCi(jTextFielCI.getText());
        s.setNombre(jTextFieldNOMBRE.getText());
        s.setApellido(jTextFieldAPELLIDO.getText());
        s.setSexo(jTextFieldSEXO.getText());
        s.setTipo(jTextFieldTIPO.getText());
        s.setCorreo(jTextFieldCORREO.getText());
        s.setCel_ref(jTextFieldCELULAR.getText());
        s.setFecha_i(jTextFieldFECHA_I.getText());
        s.setFEcha_f(jTextFieldFECHA_F.getText());
        s.setVelocidad_t(jTextFielVELOCIDAD_T.getText());
        s.InsertarSecre();
        s.MostrarSecre(jTablesECRETARIA);
        this.limpiar();
    }//GEN-LAST:event_jButtonguardarActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        // TODO add your handling code here:
        s.setCi(jTextFielCI.getText());
        s.setNombre(jTextFieldNOMBRE.getText());
        s.setApellido(jTextFieldAPELLIDO.getText());
        s.setSexo(jTextFieldSEXO.getText());
        s.setTipo(jTextFieldTIPO.getText());
        s.setCorreo(jTextFieldCORREO.getText());
        s.setCel_ref(jTextFieldCELULAR.getText());
        s.setFecha_i(jTextFieldFECHA_I.getText());
        s.setFEcha_f(jTextFieldFECHA_F.getText());
        s.setVelocidad_t(jTextFielVELOCIDAD_T.getText());
        s.ModificarSecre();
        s.MostrarSecre(jTablesECRETARIA);
        this.limpiar();
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeleccionarActionPerformed
        // TODO add your handling code here:
        int fila =jTablesECRETARIA.getSelectedRow();
        if (fila > -1){
            String idP = jTablesECRETARIA.getValueAt(fila, 0).toString();
            String Nombre = jTablesECRETARIA.getValueAt(fila, 1).toString();
            String Apellido = jTablesECRETARIA.getValueAt(fila, 2).toString();
            String sexo = jTablesECRETARIA.getValueAt(fila, 3).toString();
            String Tipo = jTablesECRETARIA.getValueAt(fila, 4).toString();
            String correo = jTablesECRETARIA.getValueAt(fila, 5).toString();
            String cel_ref = jTablesECRETARIA.getValueAt(fila, 6).toString();
            String Fecha_i = jTablesECRETARIA.getValueAt(fila, 7).toString();
            String fecha_f = jTablesECRETARIA.getValueAt(fila, 8) != null ? jTablesECRETARIA.getValueAt(fila, 8).toString() : "";
            String velocidad = jTablesECRETARIA.getValueAt(fila, 9).toString();
            
        jTextFielCI.setText(idP);
        jTextFieldNOMBRE.setText(Nombre);
        jTextFieldAPELLIDO.setText(Apellido);
        jTextFieldSEXO.setText(sexo);
        jTextFieldTIPO.setText(Tipo);
        jTextFieldCORREO.setText(correo);
        jTextFieldCELULAR.setText(cel_ref);
        jTextFieldFECHA_I.setText(Fecha_i);
        jTextFieldFECHA_F.setText(fecha_f);
        jTextFielVELOCIDAD_T.setText(velocidad);
        }
    }//GEN-LAST:event_jButtonSeleccionarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        // TODO add your handling code here:
        s.setCi(jTextFielCI.getText());
        s.EliminarSecre();
        s.MostrarSecre(jTablesECRETARIA);
        this.limpiar();
        
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonatrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonatrasActionPerformed
        // TODO add your handling code here:
        new JF_PrincipalPersonal().setVisible(true);
        JF_Secretaria.jButtonSeleccionarId.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_jButtonatrasActionPerformed

    private void jTextFieldTIPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTIPOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTIPOActionPerformed

    private void jButtonSeleccionarIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeleccionarIdActionPerformed
        int fila =jTablesECRETARIA.getSelectedRow();
        if (fila > -1){
            String id = jTablesECRETARIA.getValueAt(fila, 0).toString();
            if(JF_niños.niñoss!=null && JF_niños.niñoss.isVisible()){
                JF_niños.niñoss.jTextIDCIsecre.setText(id);
                JF_Secretaria.jButtonatras.setEnabled(true);
                JF_Secretaria.jButtonNuevo.setEnabled(true);
                JF_Secretaria.jButtonModificar.setEnabled(true);
                JF_Secretaria.jButtonguardar.setEnabled(true);
                JF_Secretaria.jButtonEliminar.setEnabled(true);
                JF_Secretaria.jButtonSeleccionar.setEnabled(true);
                JF_Secretaria.jLabelSecretaria.setText("");
            }
            if(JF_Ingreso.OficialIngreso!=null&&JF_Ingreso.OficialIngreso.isVisible()){
                JF_Ingreso.OficialIngreso.jTextFieldCisecre.setText(id);
                JF_Secretaria.jButtonNuevo.setEnabled(true);
                JF_Secretaria.jButtonModificar.setEnabled(true);
                JF_Secretaria.jButtonguardar.setEnabled(true);
                JF_Secretaria.jButtonEliminar.setEnabled(true);
                JF_Secretaria.jButtonatras.setEnabled(true);
                JF_Secretaria.jButtonSeleccionar.setEnabled(true);
                JF_Secretaria.jLabelSecretaria.setText("");
            }
        }
                 
         this.dispose();
    }//GEN-LAST:event_jButtonSeleccionarIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Secretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Secretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Secretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Secretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Secretaria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButtonEliminar;
    public static javax.swing.JButton jButtonModificar;
    public static javax.swing.JButton jButtonNuevo;
    public static javax.swing.JButton jButtonSeleccionar;
    public static javax.swing.JButton jButtonSeleccionarId;
    public static javax.swing.JButton jButtonatras;
    public static javax.swing.JButton jButtonguardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JLabel jLabelSecretaria;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablesECRETARIA;
    private javax.swing.JTextField jTextFielCI;
    private javax.swing.JTextField jTextFielVELOCIDAD_T;
    private javax.swing.JTextField jTextFieldAPELLIDO;
    private javax.swing.JTextField jTextFieldCELULAR;
    private javax.swing.JTextField jTextFieldCORREO;
    private javax.swing.JTextField jTextFieldFECHA_F;
    private javax.swing.JTextField jTextFieldFECHA_I;
    private javax.swing.JTextField jTextFieldNOMBRE;
    private javax.swing.JTextField jTextFieldSEXO;
    private javax.swing.JTextField jTextFieldTIPO;
    // End of variables declaration//GEN-END:variables
}
