/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package j_frame;

/**
 *
 * @author byvagner
 */
import clases.T_ingreso;

public class JF_T_ingreso extends javax.swing.JFrame {

    /**
     * Creates new form JF_T_ingreso
     */
    T_ingreso ti = new T_ingreso() ;
    
    public JF_T_ingreso() {
        initComponents(); 
        this.setLocationRelativeTo(null);
        ti.MostrarJtableTI(jTableTipoIngreso);
        this.LogearT_ingreso();
    }
    
    public void limpiar (){
        jTextFieldID.setText(" ");
        jTextFieldDescripcion.setText("");
    }
    public void LogearT_ingreso(){
        switch(JF_principal.valiladorPrincipal){
            case"1":
                JF_T_ingreso.jButtonNuevo.setEnabled(false);
                JF_T_ingreso.jButtonGuardar.setEnabled(false);
                JF_T_ingreso.jButtonModificar.setEnabled(false);
                JF_T_ingreso.jButtonEliminar.setEnabled(false);
                JF_T_ingreso.jButtonSeleccionar.setEnabled(false);
                JF_T_ingreso.jButtonSeleccionarID.setEnabled(false);
                break;
            case"2":
                break;
            case"3":
            case"4":
                JF_T_ingreso.jButtonEliminar.setEnabled(false);
                break;
            default:
                break;               
        }
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldDescripcion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTipoIngreso = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButtonSeleccionar = new javax.swing.JButton();
        jButtonNuevo = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonSeleccionarID = new javax.swing.JButton();
        jButtonatras = new javax.swing.JButton();
        jLabelTIPOiNGRESO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Tipo de Igreso ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 140, -1));
        jPanel1.add(jTextFieldID, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 40, -1));

        jLabel2.setText("ID ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel3.setText("Descripcion");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));
        jPanel1.add(jTextFieldDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 110, -1));

        jTableTipoIngreso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableTipoIngreso);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 460, 160));

        jLabel4.setText("operaciones ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, -1, -1));

        jButtonSeleccionar.setText("SELECCIONAR");
        jButtonSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeleccionarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, 150, -1));

        jButtonNuevo.setText("Nuevo ");
        jButtonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, 90, -1));

        jButtonGuardar.setText("Guardar ");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, 90, -1));

        jButtonModificar.setText("Modificar ");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, 90, -1));

        jButtonEliminar.setText("Eliminar ");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, 90, -1));

        jButtonSeleccionarID.setText("SELECCIONAR ID ");
        jButtonSeleccionarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeleccionarIDActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSeleccionarID, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, 170, -1));

        jButtonatras.setText("Atras");
        jButtonatras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonatrasActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonatras, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 470, 90, -1));
        jPanel1.add(jLabelTIPOiNGRESO, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 430, 240, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoActionPerformed
        
        this.limpiar(); 
        
    }//GEN-LAST:event_jButtonNuevoActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
            ti.setInTi(jTextFieldID.getText());
            ti.setDescripcion(jTextFieldDescripcion.getText());
            ti.InsertarTI();
            ti.MostrarJtableTI(jTableTipoIngreso);
            this.limpiar();
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        
        ti.setInTi(jTextFieldID.getText());
        ti.setDescripcion(jTextFieldDescripcion.getText());
        ti.ModificarTI();
        ti.MostrarJtableTI(jTableTipoIngreso);
        this.limpiar();
        
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        
        ti.setInTi(jTextFieldID.getText());
        ti.EliminarTI();
        ti.MostrarJtableTI(jTableTipoIngreso);
        this.limpiar();
        
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeleccionarActionPerformed
        // TODO add your handling code here:
        int fila =jTableTipoIngreso.getSelectedRow();
        if (fila > -1){
            String id = jTableTipoIngreso.getValueAt(fila, 0).toString();
            String Descripcion = jTableTipoIngreso.getValueAt(fila, 1).toString();
            
            jTextFieldID.setText(id);
            jTextFieldDescripcion.setText(Descripcion);
            
        }
    }//GEN-LAST:event_jButtonSeleccionarActionPerformed

    private void jButtonSeleccionarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeleccionarIDActionPerformed
        
        int fila =jTableTipoIngreso.getSelectedRow();
        if (fila > -1){
            String id = jTableTipoIngreso.getValueAt(fila, 0).toString();
             if(JF_Ingreso.OficialIngreso!=null&&JF_Ingreso.OficialIngreso.isVisible()){
                JF_Ingreso.OficialIngreso.jTextFieldIDIngresooo.setText(id);
                JF_T_ingreso.jButtonatras.setEnabled(true);
                JF_T_ingreso.jButtonNuevo.setEnabled(true);
                JF_T_ingreso.jButtonGuardar.setEnabled(true);
                JF_T_ingreso.jButtonModificar.setEnabled(true);
                JF_T_ingreso.jButtonEliminar.setEnabled(true);
                JF_T_ingreso.jButtonSeleccionar.setEnabled(true);
                JF_T_ingreso.jLabelTIPOiNGRESO.setText("");
            }
        }
        this.dispose();
    }//GEN-LAST:event_jButtonSeleccionarIDActionPerformed

    private void jButtonatrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonatrasActionPerformed
        new JF_principal().setVisible(true);
        JF_T_ingreso.jButtonSeleccionarID.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_jButtonatrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_T_ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_T_ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_T_ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_T_ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_T_ingreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButtonEliminar;
    public static javax.swing.JButton jButtonGuardar;
    public static javax.swing.JButton jButtonModificar;
    public static javax.swing.JButton jButtonNuevo;
    public static javax.swing.JButton jButtonSeleccionar;
    public static javax.swing.JButton jButtonSeleccionarID;
    public static javax.swing.JButton jButtonatras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabelTIPOiNGRESO;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTipoIngreso;
    private javax.swing.JTextField jTextFieldDescripcion;
    private javax.swing.JTextField jTextFieldID;
    // End of variables declaration//GEN-END:variables
}
