/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package j_frame;

/**
 *
 * @author byvagner
 */
import clases.*;
import static j_frame.JF_Personal.jButtonModificar;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JButton;

public class JF_tutor extends javax.swing.JFrame {

    /**
     * Creates new form JF_tutor
     */
   tutor t = new tutor();

   
    public JF_tutor() {
        initComponents();
        
        
            customizeButton(jButtonEliminar);
    customizeButton(jButtonGuardar);
    customizeButton(jButtonModificar);
    customizeButton(jButtonNuevo);
    customizeButton(jButtonSeleID);
    customizeButton(jButtonSeleccionar);
    customizeButton(jButtonatras);
    
    
    
        this.setLocationRelativeTo(null);
        t.MostrarJtableTI(jTabletutor);
        this.logear();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabletutor = new javax.swing.JTable();
        jButtonSeleccionar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldDescripcion = new javax.swing.JTextField();
        jTextFieldNomvbre = new javax.swing.JTextField();
        jTextFieldapellido = new javax.swing.JTextField();
        jTextFieldsexo = new javax.swing.JTextField();
        jTextFieldcelular = new javax.swing.JTextField();
        jTextFieldiereccion = new javax.swing.JTextField();
        jTextFieldIDDD = new javax.swing.JTextField();
        jButtonNuevo = new javax.swing.JButton();
        jButtonModifcar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jButtonSeleID = new javax.swing.JButton();
        jButtonatras = new javax.swing.JButton();
        jLabelRTexto = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 255, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("TUTOR");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 140, 30));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTabletutor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTabletutor);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 690, 220));

        jButtonSeleccionar.setText("SELECCIONAR ");
        jButtonSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeleccionarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 320, 140, -1));

        jScrollPane2.setViewportView(jTextPane1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 580, 880, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("DESCRIPCION");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("NOMBRE");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("APELLIDO");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("SEXO");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("CEL");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("DIRECCION");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jLabel8.setBackground(new java.awt.Color(51, 51, 51));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("ID");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 30, -1));
        jPanel1.add(jTextFieldDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 90, -1));
        jPanel1.add(jTextFieldNomvbre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 90, -1));
        jPanel1.add(jTextFieldapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 90, -1));
        jPanel1.add(jTextFieldsexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 40, -1));
        jPanel1.add(jTextFieldcelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 90, -1));
        jPanel1.add(jTextFieldiereccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 90, -1));

        jTextFieldIDDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDDDActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldIDDD, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 40, -1));

        jButtonNuevo.setText("nuevo");
        jButtonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 90, -1));

        jButtonModifcar.setText("modificar");
        jButtonModifcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifcarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonModifcar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 90, -1));

        jButtonEliminar.setText("eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 90, -1));

        jButtonGuardar.setText("guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 90, -1));

        jButtonSeleID.setText("SELECCIONAR ID ");
        jButtonSeleID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeleIDActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSeleID, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 320, 160, -1));

        jButtonatras.setText("atras");
        jButtonatras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonatrasActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonatras, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 550, 110, -1));
        jPanel1.add(jLabelRTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, 290, 20));

        jPanel2.setBackground(new java.awt.Color(80, 144, 175));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 230, 220));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/6.jpeg"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 914, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void limpiar(){
        jTextFieldIDDD.setText("");
        jTextFieldDescripcion.setText("");
        jTextFieldNomvbre.setText("");
        jTextFieldapellido.setText("");
        jTextFieldsexo.setText("");
        jTextFieldcelular.setText("");
        jTextFieldiereccion.setText("");
    }
    public void logear(){
        switch( JF_principal.valiladorPrincipal){
            case"1":
                JF_tutor.jButtonNuevo.setEnabled(false);
                JF_tutor.jButtonGuardar.setEnabled(false);
                JF_tutor.jButtonModifcar.setEnabled(false);
                JF_tutor.jButtonEliminar.setEnabled(false);
                JF_tutor.jButtonSeleccionar.setEnabled(false);
                JF_tutor.jButtonSeleID.setEnabled(false);     
                break;
            case"2":
                 break;
            case"3":
            case"4":
                JF_tutor.jButtonEliminar.setEnabled(false);
                 break;
            default:
                break;
        }
    }
private void customizeButton(JButton button) {
    button.setPreferredSize(new Dimension(200, 50));
    button.setFocusPainted(false);
    button.setBorderPainted(false);
    button.setContentAreaFilled(false);
    button.setOpaque(true); // Fondo no transparente

    // Colores más fuertes
    Color normalColor = new Color(100, 149, 237); // Azul claro fuerte
    Color hoverColor = new Color(70, 130, 180); // Azul intermedio
    Color pressColor = new Color(30, 60, 120); // Azul oscuro

    // Establece el color inicial del fondo
    button.setBackground(normalColor);
    button.setForeground(Color.WHITE); // Texto en blanco
    button.setFont(new Font("Arial", Font.BOLD, 16));

    // Bordes redondeados usando 'setBorder' directamente
    button.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0), 2)); // Borde negro

    // Agregar efectos de cambio de color y sombra
    button.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            // Efecto de cambio de color suave
            button.setBackground(hoverColor); // Color cuando el cursor entra
            button.setCursor(new Cursor(Cursor.HAND_CURSOR)); // Cambia el cursor

            // Sombra dinámica
            button.setBorder(BorderFactory.createLineBorder(new Color(50, 50, 50), 3)); // Cambia el borde a más grueso
        }

        @Override
        public void mouseExited(java.awt.event.MouseEvent evt) {
            button.setBackground(normalColor); // Vuelve al color normal
            button.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0), 2)); // Vuelve al borde normal
        }

        @Override
        public void mousePressed(java.awt.event.MouseEvent evt) {
            button.setBackground(pressColor); // Color cuando se presiona
        }

        @Override
        public void mouseReleased(java.awt.event.MouseEvent evt) {
            button.setBackground(hoverColor); // Vuelve al color de hover después de soltar
        }
    });
}


    
    
    
    private void jButtonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoActionPerformed
        // TODO add your handling code here:
       this.limpiar();
    }//GEN-LAST:event_jButtonNuevoActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
        t.setIdT(jTextFieldIDDD.getText());
        t.setDescripcion(jTextFieldDescripcion.getText());
        t.setNombre(jTextFieldNomvbre.getText());
        t.setApellido(jTextFieldapellido.getText());
        t.setSexo(jTextFieldsexo.getText());
        t.setCel(jTextFieldcelular.getText());
        t.setDireccion(jTextFieldiereccion.getText());
        t.guardar();
        t.MostrarJtableTI(jTabletutor);
        this.limpiar();
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonModifcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifcarActionPerformed
        // TODO add your handling code here:
        t.setIdT(jTextFieldIDDD.getText());
        t.setDescripcion(jTextFieldDescripcion.getText());
        t.setNombre(jTextFieldNomvbre.getText());
        t.setApellido(jTextFieldapellido.getText());
        t.setSexo(jTextFieldsexo.getText());
        t.setCel(jTextFieldcelular.getText());
        t.setDireccion(jTextFieldiereccion.getText());
        t.modificar();
        t.MostrarJtableTI(jTabletutor);
        this.limpiar();
    }//GEN-LAST:event_jButtonModifcarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        // TODO add your handling code here:
        t.setIdT(jTextFieldIDDD.getText());
        t.eliminar();
        t.MostrarJtableTI(jTabletutor);
        this.limpiar();
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeleccionarActionPerformed
        // TODO add your handling code here:
        int fila =jTabletutor.getSelectedRow();
        if (fila > -1){
            String uno = jTabletutor.getValueAt(fila, 0).toString();
            String dos = jTabletutor.getValueAt(fila, 1).toString();
            String tres = jTabletutor.getValueAt(fila, 2).toString();
            String cuatro = jTabletutor.getValueAt(fila, 3).toString();
            String cinco = jTabletutor.getValueAt(fila, 4).toString();
            String seis = jTabletutor.getValueAt(fila, 5).toString();
            String siete = jTabletutor.getValueAt(fila, 6).toString();
            
            jTextFieldIDDD.setText(uno);
            jTextFieldDescripcion.setText(dos);
            jTextFieldNomvbre.setText(tres);
            jTextFieldapellido.setText(cuatro);
            jTextFieldsexo.setText(cinco);
            jTextFieldcelular.setText(seis);
            jTextFieldiereccion.setText(siete);
         
        }
    }//GEN-LAST:event_jButtonSeleccionarActionPerformed

    private void jButtonSeleIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeleIDActionPerformed
       
        int fila =jTabletutor.getSelectedRow();
        if (fila > -1){
            String id = jTabletutor.getValueAt(fila, 0).toString();
            if(JF_niños.niñoss!=null && JF_niños.niñoss.isVisible()){
                JF_niños.niñoss.jTextIDTutor.setText(id);   
                JF_tutor.jButtonatras.setEnabled(true);      
                JF_tutor.jButtonNuevo.setEnabled(true);
                JF_tutor.jButtonGuardar.setEnabled(true);
                JF_tutor.jButtonModifcar.setEnabled(true);
                JF_tutor.jButtonEliminar.setEnabled(true);
                JF_tutor.jButtonSeleccionar.setEnabled(true);
                JF_tutor.jLabelRTexto.setText("");
            }
        }
        this.dispose();
    }//GEN-LAST:event_jButtonSeleIDActionPerformed

    private void jButtonatrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonatrasActionPerformed
        // TODO add your handling code here:
        new JF_principal().setVisible(true);
        JF_tutor.jButtonSeleID.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_jButtonatrasActionPerformed

    private void jTextFieldIDDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDDDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDDDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_tutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_tutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_tutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_tutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_tutor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButtonEliminar;
    public static javax.swing.JButton jButtonGuardar;
    public static javax.swing.JButton jButtonModifcar;
    public static javax.swing.JButton jButtonNuevo;
    public static javax.swing.JButton jButtonSeleID;
    public static javax.swing.JButton jButtonSeleccionar;
    public static javax.swing.JButton jButtonatras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JLabel jLabelRTexto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTabletutor;
    private javax.swing.JTextField jTextFieldDescripcion;
    private javax.swing.JTextField jTextFieldIDDD;
    private javax.swing.JTextField jTextFieldNomvbre;
    private javax.swing.JTextField jTextFieldapellido;
    private javax.swing.JTextField jTextFieldcelular;
    private javax.swing.JTextField jTextFieldiereccion;
    private javax.swing.JTextField jTextFieldsexo;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
