/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package j_frame;

/**
 *
 * @author byvagner
 */
import clases.UE;
import j_frame.JF_operaciones;

public class JF_UE extends javax.swing.JFrame {

    /**
     * Creates new form JF_UE
     */
    UE ue = new UE();
    
    public JF_UE() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        ue.MostrarJt(jtableUE);
        this.LogearUE();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFiedID = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldDireccion = new javax.swing.JTextField();
        jTextFieldcel = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableUE = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jButtonnuevo = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonEliminarrrr = new javax.swing.JButton();
        jButtonSeleccioar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonseleID = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Unidad Educativas ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 130, 30));

        jLabel2.setText("NOMBRE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel3.setText("DIRECCION");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel4.setText("CEL");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel5.setText("ID");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 110, 30, -1));
        jPanel1.add(jTextFiedID, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 40, -1));
        jPanel1.add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 100, -1));

        jTextFieldDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDireccionActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 120, -1));
        jPanel1.add(jTextFieldcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 110, -1));

        jtableUE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtableUE);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, 120));

        jLabel6.setText("operaciones");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, -1, -1));

        jButtonnuevo.setText("Nuevo ");
        jButtonnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonnuevoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 110, -1));

        jButtonGuardar.setText("Guardar ");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 110, -1));

        jButtonModificar.setText("Modificar ");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, 110, -1));

        jButtonEliminarrrr.setText("Eliminar ");
        jButtonEliminarrrr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarrrrActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEliminarrrr, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 110, -1));

        jButtonSeleccioar.setText("SELECCIONAR");
        jButtonSeleccioar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeleccioarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSeleccioar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 120, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 730, -1));

        jButtonseleID.setText("SELECCIONAR ID ");
        jButtonseleID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonseleIDActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonseleID, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, 140, -1));

        jButton2.setText("Atras");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 510, 100, -1));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, 180, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDireccionActionPerformed
    public void Limpiar (){
        jTextFiedID.setText("");
        jTextFieldNombre.setText("");
        jTextFieldDireccion.setText("");
        jTextFieldcel.setText("");
    }
    public void LogearUE(){
        switch(JF_principal.valiladorPrincipal){
            case"1":
                JF_UE.jButtonnuevo.setEnabled(false);
                JF_UE.jButtonGuardar.setEnabled(false);
                JF_UE.jButtonModificar.setEnabled(false);
                JF_UE.jButtonEliminarrrr.setEnabled(false);
                JF_UE.jButtonseleID.setEnabled(false);
                JF_UE.jButtonSeleccioar.setEnabled(false);
                break;
            case"2":
                break;
            case"3":
            case"4":
                JF_UE.jButtonEliminarrrr.setEnabled(false);
                break;
            default:
                break;               
        }
    }
    private void jButtonnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonnuevoActionPerformed
        // TODO add your handling code here:
        this.Limpiar();
    }//GEN-LAST:event_jButtonnuevoActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
        ue.setIdUE( jTextFiedID.getText());
        ue.setNombre(jTextFieldNombre.getText());
        ue.setDireccion(jTextFieldDireccion.getText());
        ue.setCel_ref(jTextFieldcel.getText());
        ue.Insertar();
        
        ue.MostrarJt(jtableUE);
        this.Limpiar();
        
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        // TODO add your handling code here:
        ue.setIdUE( jTextFiedID.getText());
        ue.setNombre(jTextFieldNombre.getText());
        ue.setDireccion(jTextFieldDireccion.getText());
        ue.setCel_ref(jTextFieldcel.getText());
        ue.Modificar();
        
        ue.MostrarJt(jtableUE);
        this.Limpiar();
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonEliminarrrrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarrrrActionPerformed
        // TODO add your handling code here:
        ue.setIdUE(jTextFiedID.getText() );
        ue.eliminar();
        ue.MostrarJt(jtableUE);
        this.Limpiar();
        
    }//GEN-LAST:event_jButtonEliminarrrrActionPerformed

    private void jButtonSeleccioarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeleccioarActionPerformed
        // TODO add your handling code here:
          int fila =jtableUE.getSelectedRow();
        if (fila > -1){
            String idUE = jtableUE.getValueAt(fila, 0).toString();
            String Nombre = jtableUE.getValueAt(fila, 1).toString();
            String Direccion = jtableUE.getValueAt(fila, 2).toString();
            String cel_ref = jtableUE.getValueAt(fila, 3).toString();
            
            jTextFiedID.setText(idUE);
            jTextFieldNombre.setText(Nombre);
            jTextFieldDireccion.setText(Direccion);
            jTextFieldcel.setText(cel_ref);
        }
        
    }//GEN-LAST:event_jButtonSeleccioarActionPerformed

    private void jButtonseleIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonseleIDActionPerformed
        int fila =jtableUE.getSelectedRow();
        if (fila > -1){
           String id = jtableUE.getValueAt(fila, 0).toString();
           if (JF_formacion.OficialFormacion != null && JF_formacion.OficialFormacion.isVisible()) {
            JF_formacion.OficialFormacion.jTextFieldIDUE.setText(id);
            JF_UE.jButtonnuevo.setEnabled(true);
            JF_UE.jButtonGuardar.setEnabled(true);
            JF_UE.jButtonModificar.setEnabled(true);
            JF_UE.jButtonEliminarrrr.setEnabled(true);
            JF_UE.jButton2.setEnabled(true);
            JF_UE.jButtonSeleccioar.setEnabled(false);
            JF_UE.jLabel7.setText("");
        }
            if (JF_principal.operaciones != null && JF_principal.operaciones.isVisible()) {
            JF_principal.operaciones.jTextFieldIDUE.setText(id);
        }
           
           this.dispose();
        } 
    }//GEN-LAST:event_jButtonseleIDActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new JF_principal().setVisible(true);
        JF_UE.jButtonseleID.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_UE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_UE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_UE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_UE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_UE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButton2;
    public static javax.swing.JButton jButtonEliminarrrr;
    public static javax.swing.JButton jButtonGuardar;
    public static javax.swing.JButton jButtonModificar;
    public static javax.swing.JButton jButtonSeleccioar;
    public static javax.swing.JButton jButtonnuevo;
    public static javax.swing.JButton jButtonseleID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFiedID;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldcel;
    private javax.swing.JTable jtableUE;
    // End of variables declaration//GEN-END:variables
}
